apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: keycloak-servicemonitor
  namespace: identity
  labels:
    release: kube-prometheus-stack
spec:
  endpoints:
    - port: http
      path: /realms/master/metrics
      interval: 30s
  selector:
    matchLabels:
      app.kubernetes.io/name: keycloak
  namespaceSelector:
    matchNames:
      - identity
